### ISSUE TITLE
Broken empty linestring repr with last s2geography dev version

### ISSUE THREAD

**Issue by benbovy** [benbovy/spherely#67]
Looks like the CI failing tests are caused by the changes in https://github.com/paleolimbot/s2geography/pull/37, which now raises an exception for empty S2Polyline. @jorisvandenbossche do you think we should fix that in s2geography or work around it in spherely to support empty linestrings?

**Comment by benbovy** [comment]
Yeah the creation functions added in #51 currently add one empty polyline, but it is probably cleaner indeed to implement the empty case as no polyline here (there might actually be another bug since actually `Geography.m_empty` is set to true when there is no polyline and not an empty polyline).

**Comment by jorisvandenbossche** [comment]
In any case, `"LINESTRING EMPTY"` is being tested on the s2geography side, so I assume the creation methods there also create a PolylineGeography with an empty vector

**Comment by benbovy** [comment]
Yes we should fix this in the Spherely creation functions.
