### ISSUE TITLE
Scalar creation functions: add oriented and planar parameters

### ISSUE THREAD

**Issue by benbovy** [benbovy/spherely#75]
Add `oriented` and `planar` (and `tessellate_tolerance`) parameters to the scalar geography creation functions (where appropriate) so it is consistent with the Input functions.

**Comment by benbovy** [comment]
I actually don't think this is worth it.

For input functions (`from_wkt`, `from_wkb`, etc.) the `planar=True` option makes sense since we may want to import data that has been created elsewhere using a planar geometry engine like Shapely. When creating `spherely.Geography` objects from scratch let's assume we are directly operating on the sphere.

I also don't think `oriented=True` is very useful for scalar creation functions. It will probably be more useful for vectorized creation functions.

(cc @jorisvandenbossche in case you have any thoughts on this).

**Comment by benbovy** [comment]
> I also don't think `oriented=True` is very useful for scalar creation functions. It will probably be more useful for vectorized creation functions.

I was only considering performance. Maybe this is still useful in the (rare?) case of creating polygons where the interior is larger than the hemisphere?

**Comment by jorisvandenbossche** [comment]
Indeed, I think the `oriented` keyword is still useful for that use case
